guid: 000a47010f094079
video_mode: 640x480_mono8
frame_rate: 30.0
bayer_pattern: "HQ"
bayer_method: "Simple"
frame_id: frame2
camera_info_url: package://dcsl_vision_tracker/config/000a47010f094079.yaml
