guid: 000a47010f0a58ee
video_mode: 640x480_mono8
frame_rate: 30.0
bayer_pattern: "rggb"
bayer_method: "HQ"
frame_id: frame4
camera_info_url: package://dcsl_vision_tracker/config/000a47010f0a58ee.yaml
