guid: 000a47010f0940ba
video_mode: 1024x768_mono8
frame_rate: 15.0
frame_id: frame0
auto_brightness: 3
brightness: 25
auto_exposure: 3
exposure: 100
auto_gain: 3
gain: 680
auto_gamma: 0
auto_shutter: 3
shutter: 1800
camera_info_url: package://dcsl_vision_tracker/config/000a47010f0940ba.yaml
